### ISSUE TITLE
npm install fails with sharp code 1 on raspberry/debian/x86_64 virtual machine

### ISSUE THREAD

**Issue by adrianrath** [darickc/MMM-BackgroundSlideshow#111]
Hi - I have installed Magic mirror successfully for the first time. I have added in a number of modules including MMM-GooglePhotos with no issues. I would like to get BackgroundSlideshow running but it is throwing compilation errors that I am not sure how to solve. Any ideas? Many thanks.
Adrian

[2021-12-31T02_28_42_423Z-debug.log](https://github.com/darickc/MMM-BackgroundSlideshow/files/7795724/2021-12-31T02_28_42_423Z-debug.log)

266 timing build:link:node_modules/semver Completed in 5ms
267 timing build:link Completed in 6ms
268 info run sharp@0.28.2 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
269 info run sharp@0.28.2 install { code: 1, signal: null }
270 timing reify:rollback:createSparse Completed in 373ms
271 timing reify:rollback:retireShallow Completed in 0ms
272 timing command:install Completed in 9599ms
273 verbose stack Error: command failed
273 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)

**Comment by Dotmatrix812** [comment]
Kind of same Problem here. After Update to MM 2.18.0

`0|MagicMir | [03.01.2022 12:03.29.131] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: 'linux-armv7' binaries cannot be used on the 'linux-armvdefault' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-armvdefault' platform.
0|MagicMir | [03.01.2022 12:03.29.185] [ERROR] App threw an error during load
0|MagicMir | [03.01.2022 12:03.29.190] [ERROR] Error: 'linux-armv7' binaries cannot be used on the 'linux-armvdefault' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-armvdefault' platform.
0|MagicMir |     at Object.hasVendoredLibvips (/home/pi/MagicMirror/modules/MMM-BackgroundSlideshow/node_modules/sharp/lib/libvips.js:82:13)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-BackgroundSlideshow/node_modules/sharp/lib/constructor.js:7:22)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1116:14)
0|MagicMir |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:988:32)
0|MagicMir |     at Module._load (node:internal/modules/cjs/loader:829:12)
0|MagicMir |     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:94:18)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-BackgroundSlideshow/node_modules/sharp/lib/index.js:3:15)
0|MagicMir | [03.01.2022 12:03.29.193] [ERROR] Whoops! There was an uncaught exception...
0|MagicMir | [03.01.2022 12:03.29.202] [ERROR] Error: 'linux-armv7' binaries cannot be used on the 'linux-armvdefault' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-armvdefault' platform.
0|MagicMir |     at Object.hasVendoredLibvips (/home/pi/MagicMirror/modules/MMM-BackgroundSlideshow/node_modules/sharp/lib/libvips.js:82:13)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-BackgroundSlideshow/node_modules/sharp/lib/constructor.js:7:22)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1116:14)
0|MagicMir |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:988:32)
0|MagicMir |     at Module._load (node:internal/modules/cjs/loader:829:12)
0|MagicMir |     at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:94:18)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-BackgroundSlideshow/node_modules/sharp/lib/index.js:3:15)
0|MagicMir | [03.01.2022 12:03.29.205] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMir | [03.01.2022 12:03.29.207] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|MagicMir | [6319:0103/120331.008276:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
0|MagicMir | [6342:0103/120331.415731:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
`
