### ISSUE TITLE
where to set unhandled-rejections=strict

### ISSUE THREAD

**Issue by atlantus-eng** [darickc/MMM-BackgroundSlideshow#150]
Get following error:
D:\MagicMirror>npm run start

> magicmirror@2.25.0 start
> .\node_modules\.bin\electron js\electron.js

[26.01.2024 08:01.45.940] [LOG]   Starting MagicMirror: v2.25.0
[26.01.2024 08:01.45.949] [LOG]   Loading config ...
[26.01.2024 08:01.45.971] [DEBUG] config template file not exists, no envsubst
[26.01.2024 08:01.45.988] [LOG]   Loading module helpers ...
[26.01.2024 08:01.46.071] [ERROR] (node:15132) UnhandledPromiseRejectionWarning: Error: Cannot find module 'jimp'
Require stack:
- D:\MagicMirror\modules\MMM-BackgroundSlideshow\node_helper.js
- D:\MagicMirror\js\app.js
- D:\MagicMirror\js\electron.js
- D:\MagicMirror\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at node:internal/modules/cjs/loader:1084:15
    at Function.<anonymous> (node:electron/js2c/browser_init:2:117419)
    at Module._resolveFilename (D:\MagicMirror\node_modules\module-alias\index.js:49:29)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\MagicMirror\modules\MMM-BackgroundSlideshow\node_helper.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadModule (D:\MagicMirror\js\app.js:180:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[26.01.2024 08:01.46.072] [ERROR] (node:15132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

Where and how to fix?

**Comment by KristjanESPERANTO** [comment]
Seems that you have not installed the dependencies as described in the README.

**Comment by KristjanESPERANTO** [comment]
@atlantus-eng Did you run `npm install` in the module's directory?

**Comment by atlantus-eng** [comment]
Thanks, it works now!
